FROM python:3
USER root
WORKDIR /app
COPY python/src /app
COPY python/requirements.txt /app
RUN pip install --upgrade pip
RUN pip install --upgrade setuptools
RUN pip install -r /app/requirements.txt
RUN apt-get update
RUN apt install -y docker.io docker-compose
# For check
# CMD ["python", "test.py"]

