services:
  # Teedyアプリケーション本体
  teedy-server:
    image: sismics/docs:v1.11
    restart: unless-stopped
    ports:
      - 8081:8080  # ホストの8081番ポートをコンテナの8080番ポートにマッピング
    environment:
      DOCS_BASE_URL: "${DOCS_BASE_URL}"  # TeedyのベースURL
      DOCS_ADMIN_EMAIL_INIT: "${DOCS_ADMIN_EMAIL_INIT}"  # 管理者メールアドレス
      DOCS_ADMIN_PASSWORD_INIT: "${DOCS_ADMIN_PASSWORD_INIT}"  # 管理者パスワード（例: "superSecure" のハッシュ値）
      DATABASE_URL: "${DATABASE_URL}"  # データベース接続設定
      DATABASE_USER: "${DATABASE_USER}"
      DATABASE_PASSWORD: "${DATABASE_PASSWORD}"
      DATABASE_POOL_SIZE: "${DATABASE_POOL_SIZE}"
    volumes:
      - ./docs/data:/data  # Teedyのデータを永続化
    networks:
      - docker-internal
      - internet
    depends_on:
      - teedy-db  # DBサービス起動後にTeedyを起動

  # Teedy用PostgreSQL
  teedy-db:
    image: postgres:13.1-alpine
    restart: unless-stopped
    expose:
      - 5432  # コンテナ間通信用に5432番ポートを公開
    environment:
      POSTGRES_USER: "teedy_db_user"
      POSTGRES_PASSWORD: "teedy_db_password"
      POSTGRES_DB: "teedy"
    volumes:
      # DBデータを永続化
      - ./docs/db:/var/lib/postgresql/data
    networks:
      - docker-internal

networks:
  # DB用の内部ネットワーク（外部アクセス不可）
  docker-internal:
    driver: bridge
    internal: true
  # Teedyサーバー用の外部ネットワーク
  internet:
    driver: bridge