version: '3'

services:
  php:
    restart: always
    build:
      context: .
      dockerfile: ./php/Dockerfile
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - meta_data:/tmp

  nginx:
    restart: always
    ports:
      - 8008:80
    build:
      context: .
      dockerfile: ./nginx/Dockerfile

  python3:
    restart: always
    build:
      context: .
      dockerfile: ./python/Dockerfile
    container_name: python3
    command: tail -f /dev/null
    volumes:
      - meta_data:/tmp

volumes:
  meta_data:
