version: '3'
services:
  nginx:
    image: nginx
    ports:
      - "48080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:rw
      - ./nginx/html:/usr/share/nginx/html
    depends_on:
      - app
  app:
    build:
      context: ./php
      dockerfile: Dockerfile
    volumes:
      - ./src:/usr/share/nginx/html
