version: '3'

services:
  php:
    restart: always
    build:
      context: .
      dockerfile: ./php/Dockerfile

  nginx:
    restart: always
    ports:
      - 8008:80
    build:
      context: .
      dockerfile: ./nginx/Dockerfile

